# Generated by Django 5.0.6 on 2024-06-03 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0005_exceldata_procurementitem_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField()),
                ('date_returned', models.DateField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.equipment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.studentinfo')),
            ],
        ),
    ]
