# Generated by Django 5.0.6 on 2024-06-03 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0007_alumni_event_jobfair_yearbook_graduateform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.equipment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.studentinfo')),
            ],
        ),
    ]
