# Generated by Django 5.0.6 on 2024-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0008_borrowingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowingrecord',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
