# Generated by Django 5.0.6 on 2024-06-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0010_accreditation_adminlogin_adviser_financialstatement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfair',
            name='applicationdeadline',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='posted_date',
            field=models.DateField(default=None),
        ),
    ]
