# Generated by Django 5.0.6 on 2024-06-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0012_studentinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='user',
        ),
    ]
