# Generated by Django 5.0.6 on 2024-06-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0017_rename_user_studentinfo_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='user_id',
        ),
    ]
