# Generated by Django 5.0.6 on 2024-06-07 23:33

import django.db.models.deletion
import django.utils.timezone
import studentLife_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0020_fileuploadtest_guidancetransaction_testarray_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='officer_position',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='student_fname',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='student_lname',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='student_mname',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='year_lvl',
        ),
        migrations.AddField(
            model_name='accreditation',
            name='date_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='date_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='student_id',
            field=models.CharField(default=7220136, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_saved',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminlogin',
            name='admin_username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('terminated', 'Terminated')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='officer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('terminated', 'Terminated')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='officerlogin',
            name='course',
            field=models.CharField(choices=[('BSIT', 'BSIT'), ('BSIE', 'BSIE'), ('BIT-COMPTECH', 'BIT-COMPTECH'), ('BIT-GARMENTS', 'BIT-GARMENTS'), ('BIT-AUTOMOTIVE', 'BIT-AUTOMOTIVE'), ('BIT-DRAFTING', 'BIT-DRAFTING'), ('BIT-ELECTRONICS', 'BIT-ELECTRONICS'), ('BEED', 'BEED'), ('BSED-MATH', 'BSED-MATH'), ('BTLED', 'BTLED'), ('BSF', 'BSF'), ('BSA', 'BSA'), ('BAL', 'BAL'), ('BAEL', 'BAEL'), ('BS-PSYCHOLOGY', 'BS-PSYCHOLOGY'), ('BSHM', 'BSHM'), ('BSTM', 'BSTM')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='officerlogin',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentLife_system.officer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_accomplishment',
            field=models.FileField(blank=True, null=True, upload_to='projects/', validators=[studentLife_system.models.validate_file_extension]),
        ),
    ]
