# Generated by Django 5.0.6 on 2024-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentLife_system', '0021_remove_officer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseling_schedule',
            name='counselingOrigin',
            field=models.CharField(default='student', max_length=20),
            preserve_default=False,
        ),
    ]
