# Generated by Django 5.0.6 on 2024-06-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_studentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentInfo',
        ),
    ]
