# Generated by Django 5.0.6 on 2024-06-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_delete_studentinfo'),
        ('studentLife_system', '0010_accreditation_adminlogin_adviser_financialstatement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentLife_system.studentinfo'),
        ),
    ]
