# Generated by Django 5.0.6 on 2024-06-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_user_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='student',
        ),
    ]
