# Generated by Django 5.0.6 on 2024-06-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_rename_student_id_user_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student',
            new_name='student_id',
        ),
    ]
