# Generated by Django 5.0.4 on 2024-06-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_alter_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('sao admin', 'Sao Admin'), ('medical admin', 'Medical Admin')], default='student', max_length=13),
        ),
    ]
